codeGenerationParameters:
  mode: single                    # single | watch
  inputFolder: './src'              # monolith folder
  outputFolder: '../distributed'  # distributed folder
  cleanOutput: true               # delete output folder before?
  generateProjects: false          # generate new npm projects?
  generateDocker: true            # generate docker files for each server?
  ignore:                         # ignore the following folders
     - "node_modules"

default:
  rabbit:
    url: myrabbit
    port: 5672
servers:
  - id: alpha
    http:
      url: localhost
      port: 3000
    functions:
    - declarationPattern: main
      method: http-get
  - id: beta
    functions:
    - declarationPattern: toUpperCase
      method: rabbit
