codeGenerationParameters:
  mode: single                  # Runs the tool a single time (instead of watching for changes)
  inputFolder: 'monolith'       # Folder where to look for the monolith code
  outputFolder: 'distributed'   # Folder to generate the microservices
  cleanOutput: false            # Instructs the tool not to clean the output folder
  generateProjects: false       # Do not generate npm projects for the microservices
  ignore:                       # Folders to ignore in the monolith
    - "node_modules"
rabbitParameters:               # Details of the RabbitMQ communication
  url: localhost
  port: 5672
  numConnectionAttempts: 5
  timeBetweenAttempts: 10    
servers:                        # Now comes the three servers
  - id: alpha                   # alpha server will contain all functions
  - id: beta                    # beta server will contain function "validatePerson", exposed
    http:                       # at localhost, port 3000, as a HTTP POST endpoint
      url: localhost
      port: 3000
    functions:
      - declarationPattern: validatePerson
        method: rabbit
  - id: gamma                   # gamma server will contain function "registerPerson", exposed
    http:                       # at localhost, port 3001, as a HTTP POST endpoint
      url: localhost
      port: 3001
    functions:
      - declarationPattern: registerPerson
        method: http-post